### ISSUE TITLE
Invalid errormessage

### ISSUE THREAD

**Issue by ghost** [subatta/ResolveUR#5] opened 2017-04-21 09:07 UTC
When using the extension I get the message below. The only thing is that the web project builds just fine...

---------------------------
Microsoft Visual Studio
---------------------------
Resolve Unused References

Project xxxxxxx already has compile errors. Please ensure it has no build errors and retry removing references.
---------------------------
OK   
---------------------------

**Extra info**
  - Visual Studio Professional 2017 Version 15.1 (26303.7) Release
  - ASP.NET Web Application (.NET Framework)

**Comment by ghost** [comment] 2017-04-25 18:57
I am having the same error with Visual Studio 2017 15.1 26403.7 Release and ResolveUR 3.3.  I have not been able to get it to work with any project type.

**Comment by IanElsinga** [comment] 2017-05-11 01:05
I can confirm that this bug affects all types of projects - even simple class libraries.

**Comment by pratyak1** [comment] 2017-05-19 16:00
I've yet to upgrade to VS 2017 15.1 26403.7. My upgrade keeps failing though I have Win 10. Will try some other things and let you guys know. Thanks for reporting.

**Comment by pratyak1** [comment] 2017-06-02 00:38
I think we found the reason for some of the errors. C# 7.0 syntax isn't supported by MSBuild version that ResolveUR finds. Issue #6 has the description. I'll soon release the version which should fix some of the error problems. So much for living on the bleeding edge of C#!

**Comment by pratyak1** [comment] 2017-06-05 15:07
@jopmiddelkamp @OHjeffhudson @IanElsinga: Could you update to v3.4 and see if your issues go away? Thanks!

**Comment by pratyak1** [comment] 2017-06-14 15:10
Closing issue as resolved.

**Closed as completed by pratyak1** 2017-06-14 15:10 UTC
Labels: bug
