### ISSUE TITLE
Project already has compile errors when there are none

### ISSUE THREAD

**Issue by sebasijan** [subatta/ResolveUR#6] opened 2017-05-14 21:20 UTC
I am having this error pop up when I try to Resolve Unused References on my project: 

 > Project MyProject already has compile errors. Please ensure it has no build errors and retry removing references.

I did originally have a compile error on another project in the same solution, but I have since completely removed that project and cleaned and rebuilt the entire solution.

After trying again I still see the same message.

Note that I am seeing this whether I select to resolve Nuget packages or not.

Has anyone else experienced this?

**Comment by Smurf-IV** [comment] 2017-05-16 14:55
Yes, I am also seeing this in Vis2017.2 Pro.
- Project did have a compile error.
- Rebuilt - Went away
- Tried this tool
- Complained as above
- Performed Clean, and rebuild
- Same outcome
- Closed studio and reopened, load solution
- Use tool, Same ..
Please fix.
Note: Solution projects are targeting .NET 4.7

**Comment by pratyak1** [comment] 2017-05-19 16:00
@Smurf-IV @sebasijan : are you guys by any chance working with VS 2017 15.1 26403.7?

**Comment by Smurf-IV** [comment] 2017-05-22 07:58
Currently 15.2 (26430.6) Release, not **7** as you have put.
VS is not showing any updates...

**Comment by sebasijan** [comment] 2017-05-22 20:51
@subatta Mine shows `Version 15.1 (26403.7) Release`

**Comment by Smurf-IV** [comment] 2017-05-23 13:57
**@sebasijan @subatta** Community / Pro / Enterprise?

**Comment by sebasijan** [comment] 2017-05-23 19:28
@Smurf-IV Community

**Comment by Allinuon** [comment] 2017-05-31 17:58
It seems to be caused by the new syntax options in C# 7 which requires MSBuild 15; ResolveUR only supports version 14 and earlier.

I added logic to check the following paths for the current MSBuild.exe:

- %VSINSTALLDIR%\\MSBuild\\%VisualStudioVersion%\\Bin\\amd64\\MSBuild.exe 
- %VSAPPIDDIR%\\..\\..\\MSBuild\\%VisualStudioVersion%\\Bin\\amd64\\MSBuild.exe
- %VSINSTALLDIR%\\MSBuild\\%VisualStudioVersion%\\Bin\\MSBuild.exe 
- %VSAPPIDDIR%\\..\\..\\MSBuild\\%VisualStudioVersion%\\Bin\\MSBuild.exe

The revised Constants.cs and MSBuildResolveUR.cs files are attached.

[ResolveUR.Library.20170531.zip](https://github.com/subatta/ResolveUR/files/1042447/ResolveUR.Library.20170531.zip)

**Comment by pratyak1** [comment] 2017-06-02 00:35
@Allinuon : I went through your files. Thanks for making those changes, they should address some of the error issues. Could you please submit a pull request? I'll merge them in so we can have a release?

**Comment by pratyak1** [comment] 2017-06-05 15:06
Thanks to @Allinuon, the issue might now be resolved. VS2017 with C# 7.0 syntax was causing issues. MSBuild paths have now been updated and build should be fine with the 3.4 version just released.

@sebasijan @Smurf-IV : could you update to this version and confirm you're good? Thanks!

**Comment by sebasijan** [comment] 2017-06-05 15:18
@subatta ~~I downloaded the zip, but have no idea where to save the files - any hints?~~

Never mind, the update appeared on VS after I posted this. Trying it out now

**Comment by sebasijan** [comment] 2017-06-05 17:28
@subatta @Allinuon It now appears to run, but takes an extremely long time, to the extent that I am pretty sure it has crashed or failed somehow. 

Not sure if I can post anything here which may be useful - let me know.

**Comment by pratyak1** [comment] 2017-06-06 22:41
@sebasijan : could you run it on couple different projects and see the same?

**Comment by pratyak1** [comment] 2017-06-14 15:10
Closing issue as resolved.

**Closed as completed by pratyak1** 2017-06-14 15:10 UTC
Labels: bug

**Comment by omsharp** [comment] 2017-10-20 21:06
I have the same issue with version 3.4 on VS2017 15.4.0

**Comment by ASPCKenneth** [comment] 2017-11-16 08:01
Same issue here on MVC project in VS2017 fully updated to last version 15.4.4
